spring.application.name=auth

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://localhost:3306/auth

spring.datasource.username=root
spring.datasource.password=1234

#spring.security.user.name=mm70
#spring.security.user.password=mm70
#spring.jpa.properties.hibernate.diaclect=org.hibernate.dialect.MYSQL5Dialect